### ISSUE TITLE
Update value only when touched.

### ISSUE THREAD

**Issue by christianmagill** [AsmodeusNOIR/acf-signature#2]
Awesome plugin! Much thanks for putting this together.

Is there anyway to avoid updating the field's value, if the user hasn't touched the field's pad?

I need to compare field values to see what a user has edited in an application I am writing.

Unfortunately, the current plugin updates the value even if the pad is never touched, and if the user's browser loads the field at a different size, the value ends up being different as well.

**Comment by christianmagill** [comment]
Here's a fix https://github.com/JamesParkNINJA/acf-signature/pull/3

**Comment by JamesParkNINJA** [comment]
Fantastic, thanks @christianmagill 
Barely able to look at stuff just now!
